owner: zuedev
repo: zuedev-upptime

sites:
  - name: Google
    url: https://www.google.com

status-website:
  baseUrl: /zuedev-upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
